language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-serverspec.gemspec
- gem install sensu-plugins-serverspec-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: LBUBZ6R/qttAz08cjgAgFt1xeZ+FSl8wOeXH+qu3iV2vK1GrsD8LbfM3017R8L0/D9M0daoFycbGA6yojXKGtTd5Ixg3GIjiTGu02I4j/PYUgoUi39pXYBRnbwO5eyrUQ6Rlc+H+rYjQTr60qB0dvFxId4bBfTadce7sKCP5CN4=
  gem: sensu-plugins-serverspec
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-serverspec
